# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='img_url',
            field=models.CharField(default='https://imgur.com/gallery/dm03l', max_length=256),
            preserve_default=False,
        ),
    ]
